const fateArr = [
    'Fate/stay night',
    'Fate/stay night Extra',
    'Fate/hollow ataraxia',
    'Fate/hollow ataraxia Extra',
    'Fate/Zero',
    'Fate/Zero Extra',
    "Lord El-Melloi II's Case Files / The Adventures of Lord El-Melloi II",
    "Lord El-Melloi II's Case Files / The Adventures of Lord El-Melloi II Extra",
    'Fate/strange Fake',
    'Fate/strange Fake Extra',
    'Fate/EXTRA / Fate/EXTRA Last Encore',
    'Fate/EXTRA / Fate/EXTRA Last Encore Extra',
    'Fate/EXTRA CCC / Fate/EXTRA CCC FoxTail',
    'Fate/EXTRA CCC / Fate/EXTRA CCC FoxTail Extra',
    'Fate/EXTELLA / Fate/EXTELLA LINK',
    'Fate/EXTELLA / Fate/EXTELLA LINK Extra',
    'Fate/Apocrypha',
    'Fate/Apocrypha Extra',
    'Fate:Lost Einherjar',
    'Fate:Lost Einherjar Extra',
    'Fate/Requiem',
    'Fate/Requiem Extra',
    'Fate/Prototype',
    'Fate/Prototype Extra',
    'Fate/Prototype: Fragments of Sky Silver',
    'Fate/Prototype: Fragments of Sky Silver Extra',
    'Fate/Labyrinth',
    'Fate/Labyrinth Extra',
    'Fate/type Redline',
    'Fate/type Redline Extra',
    'Fate/Samurai Remnant',
    'Fate/Samurai Remnant Extra',
    'Fate/Grand Order / Fate/Grand Order Arcade',
    'Fate/Grand Order / Fate/Grand Order Arcade Extra',
    'Fate/Grand Order / Fate/Grand Order Arcade non-Servants'
]
const otherTMArr = [
    "The Garden of Sinners",
    "The Garden of Sinners Extra",
    "Tsukihime",
    "Tsukihime Extra",
    "Kagetsu Tohya",
    "Kagetsu Tohya Extra",
    "Talk. / Prelude",
    "Talk. / Prelude Extra",
    "Melty Blood (Original Series)",
    "Melty Blood (Original Series) Extra",
    "Tsukihime Remake",
    "Tsukihime Remake Extra",
    "Melty Blood: Type Lumina",
    "Melty Blood: Type Lumina Extra",
    "Witch on the Holy Night",
    "Witch on the Holy Night Extra"
]
const filtersArr = [
    "Male",
    "Female",
    "Masters",
    "Servants",
    "Sabers",
    "Archers",
    "Lancers",
    "Riders",
    "Casters",
    "Assassins",
    "Berserkers",
    "Extras",
    "Rulers",
    "Avengers",
    "MoonCancers",
    "Alter Egos",
    "Foreigners",
    "Pretenders",
    "Beasts",
    "PersonalExtras"
]
const doublesKeep = [
  'palla_sov',
  'catria_sov',
  'est_sov',
  'karel_fe6',
  'bartre_fe6',
  'marcus_fe6',
  'eliwood_fe7',
  'hector_fe7',
  'murdock_fe6',
  'guinivere_fe6',
  'zephiel_fe6',
  "merlinus_fe6",
  "leif_fe5",
  "nanna_fe5",
  "finn_fe5",
  "ced_fe5",
  "diarmuid_fe5"
]
const doublesRemove = [
  'palla_fe1',
  'catria_fe1',
  'est_fe1',
  'karel_fe7',
  'bartre_fe7',
  'marcus_fe7',
  'eliwood_fe6',
  'hector_fe6',
  'murdock_fe7',
  'guinivere_fe7',
  'zephiel_fe7',
  "merlinus_fe7",
  "leif_fe4",
  "nanna_fe4",
  "finn_fe4",
  "ced_fe4",
  "diarmuid_fe4"
]
const spoilerKeep = [
  'owain',
  'severa',
  'inigo',
  'edelgard_academy',
  'edelgard_war',
  'jeritza',
  'rhea',
  'sephiran_por',
  'sephiran_rd',
  'zelgius_por',
  'zelgius_rd',
  'sirius',
  'camus',
  'camus',
  'renning_por',
  'renning_rd',
  'brigid',
  'tiki_fe13',
  'thales'
]
const spoilerRemove = [
  'odin',
  'selena_Fate:Lost Einherjar',
  'laslow',
  'flame_emperor',
  'flame_emperor',
  'death_knight',
  'seiros',
  'lehran',
  'lehran',
  'black_knight_por',
  'black_knight_rd',
  'zeke',
  'sirius',
  'zeke',
  'bertram',
  'bertram',
  'eyvel',
  'tiki_fe1',
  'lord_arundel'
]