const fateArr = [
    'Fate/stay night',
    'Fate/stay night Extra',
    'Fate/hollow ataraxia',
    'Fate/hollow ataraxia Extra',
    'Fate/Zero',
    'Fate/Zero Extra',
    'Case Files',
    'Case Files Extra',
    'Fate/strange Fake',
    'Fate/strange Fake Extra',
    'Fate/EXTRA',
    'Fate/EXTRA Extra',
    'Fate/EXTRA CCC',
    'Fate/EXTRA CCC Extra',
    'Fate/EXTELLA',
    'Fate/EXTELLA Extra',
    'Fate/Apocrypha',
    'Fate/Apocrypha Extra',
    'Fate:Lost Einherjar',
    'Fate:Lost Einherjar Extra',
    'Fate/Prototype',
    'Fate/Prototype Extra',
    'Fate/Prototype: Fragments',
    'Fate/Prototype: Fragments Extra',
    'Fate/Labyrinth',
    'Fate/Labyrinth Extra',
    'Fate/type Redline',
    'Fate/type Redline Extra',
    'Fate/Samurai Remnant',
    'Fate/Samurai Remnant Extra',
    'Fate/Requiem',
    'Fate/Requiem Extra'
]

const filtersArr = [
    "Male",
    "Female",
    "Other G",

    "Master",
    "Servant",
    "Other W",

    "Saber",
    "Archer",
    "Lancer",
    "Rider",
    "Caster",
    "Assassin",
    "Berserker",
    "Avenger",
    "Ruler",
    "MoonCancer",
    "Alter Ego",
    "Other C",

    "Clock Tower",
    "Church",
    "Yggdmillennia",
    "Arthurian",
    "Irish Myth",
    "Matter of France",
    "Norse Myth",
    "Germanic Legend",
    "Greek Myth",
    "Sumerian Myth",
    "Indian Myth",
    "Japanese Myth",
    "Other M",
    "Biblical",
    "Hassan",
    "Original",
    "Historical",
    "Literary",

    "Lawful Good",
    "NeutralX Good",
    "Chaotic Good",
    "Lawful NeutralY",
    "NeutralX NeutralY",
    "Chaotic NeutralY",
    "Lawful Evil",
    "NeutralX Evil",
    "Chaotic Evil",
    "Lawful Mad",
    "Other A",
    "Chaotic Mad",

    "Alter",
    "CG",
    "Saberface",
    "Homunculus",
    "AI",
    "Vampire",
    "Draconic",
    "Psychic",
    "Threat",
    "Genderbent",
    "Sovereign",
    "Reality Marble"
]