let library = {
    //Fate/stay night
    "saber": { "display": "Artoria Pendragon", "displayTitle": "Fate/stay night", "origin": ["Fate/stay night", "Fate/hollow ataraxia", "Fate/Zero"], "tags": ["sn", "zero"], "portrait": "sn", "class": ["Servant", "Arthurian"] },
    "archer": { "display": "EMIYA", "displayTitle": "Fate/stay night", "origin": ["Fate/stay night", "Fate/hollow ataraxia"], "tags": [], "portrait": "", "class": ["Servant"] },
    "lancer": { "display": "C\u00fa Chulainn", "displayTitle": "Fate/stay night", "origin": ["Fate/stay night", "Fate/hollow ataraxia", "Fate/EXTRA"], "tags": ["sn", "mc"], "portrait": "sn", "class": ["Servant", "Irish Myth"] },
    "rider": { "display": "Medusa", "displayTitle": "Fate/stay night", "origin": ["Fate/stay night", "Fate/hollow ataraxia"], "tags": [], "portrait": "", "class": ["Servant", "Greek Myth"] },
    "caster": { "display": "Medea", "displayTitle": "Fate/stay night", "origin": ["Fate/stay night", "Fate/hollow ataraxia"], "tags": [], "portrait": "", "class": ["Servant", "Master", "Greek Myth"] },
    "assassin": { "display": "Sasaki Kojirou", "displayTitle": "Fate/stay night", "origin": ["Fate/stay night", "Fate/hollow ataraxia"], "tags": [], "portrait": "", "class": ["Servant", "Historical"] },
    "berserker": { "display": "Heracles", "displayTitle": "Fate/stay night", "origin": ["Fate/stay night", "Fate/hollow ataraxia"], "tags": [], "portrait": "", "class": ["Servant", "Greek Myth"] },
    "gilsn": { "display": "Gilgamesh", "displayTitle": "Fate/stay night", "origin": ["Fate/stay night", "Fate/hollow ataraxia", "Fate/Zero"], "tags": [], "portrait": "", "class": ["Servant", "Sumerian Myth"] },
    "hassanca": { "display": "Hassan of the Cursed Arm", "displayTitle": "Fate/stay night", "origin": ["Fate/stay night"], "tags": [], "portrait": "", "class": ["Servant", "Hassan"] },
    "salter": { "display": "Artoria Pendragon Alter", "displayTitle": "Fate/stay night", "origin": ["Fate/stay night", "Fate/hollow ataraxia"], "tags": [], "portrait": "", "class": ["Servant", "Arthurian"] },
    "lily": { "display": "Artoria Pendragon Lily", "displayTitle": "Fate/unlimited codes", "origin": ["Fate/stay night Extra"], "tags": [], "portrait": "", "class": ["Servant", "Arthurian"] },
    "shirou": { "display": "Shirou Emiya", "displayTitle": "Fate/stay night", "origin": ["Fate/stay night", "Fate/hollow ataraxia", "Case Files", "Fate/Zero Extra"], "tags": ["sn", "lemii", "zero"], "portrait": "sn", "class": ["Master", "Clock Tower"] },
    "rin": { "display": "Rin Tohsaka", "displayTitle": "Fate/stay night", "origin": ["Fate/stay night", "Fate/hollow ataraxia", "Fate/Zero", "Case Files", "Fate/strange Fake"], "tags": ["sn", "sf", "lemii", "zero"], "portrait": "sn", "class": ["Master", "Clock Tower"] },
    "kirei": { "display": "Kirei Kotomine", "displayTitle": "Fate/stay night", "origin": ["Fate/stay night", "Fate/Zero", "Fate/strange Fake Extra"], "tags": ["sn", "zero"], "portrait": "sn", "class": ["Master", "Church"] },
    "shinji": { "display": "Shinji Matou", "displayTitle": "Fate/stay night", "origin": ["Fate/stay night", "Fate/hollow ataraxia"], "tags": [], "portrait": "", "class": ["Master"] },
    "sakura": { "display": "Sakura Matou", "displayTitle": "Fate/stay night", "origin": ["Fate/stay night", "Fate/hollow ataraxia", "Fate/Zero"], "tags": ["sn", "zero"], "portrait": "sn", "class": ["Master"] },
    "kuzuki": { "display": "Souichirou Kuzuki", "displayTitle": "Fate/stay night", "origin": ["Fate/stay night", "Fate/hollow ataraxia"], "tags": [], "portrait": "", "class": ["Master"] },
    "illya": { "display": "Illyasviel von Einzbern", "displayTitle": "Fate/stay night", "origin": ["Fate/stay night", "Fate/hollow ataraxia", "Fate/Zero Extra"], "tags": [], "portrait": "", "class": ["Master"] },
    "zouken": { "display": "Zouken Matou", "displayTitle": "Fate/stay night", "origin": ["Fate/stay night", "Fate/Zero"], "tags": [], "portrait": "", "class": ["Master", "Clock Tower"] },


    "avenger": { "display": "Angra Mainyu", "displayTitle": "Fate/hollow ataraxia", "origin": ["Fate/hollow ataraxia"], "tags": [], "portrait": "", "class": ["Servant"] },
    "gilha": { "display": "Child Gil", "displayTitle": "Fate/hollow ataraxia", "origin": ["Fate/hollow ataraxia"], "tags": [], "portrait": "", "class": ["Servant", "Sumerian Myth"] },
    "bazett": { "display": "Bazett Fraga McRemitz", "displayTitle": "Fate/hollow ataraxia", "origin": ["Fate/hollow ataraxia"], "tags": [], "portrait": "", "class": ["Master", "Clock Tower"] },
    "caren": { "display": "Caren Hortensia", "displayTitle": "Fate/hollow ataraxia", "origin": ["Fate/hollow ataraxia"], "tags": [], "portrait": "", "class": ["Master", "Church"] },


    "lancer0": { "display": "Diarmuid Ua Duibhne", "displayTitle": "Fate/Zero", "origin": ["Fate/Zero"], "tags": [], "portrait": "", "class": ["Servant", "Irish Myth"] },
    "rider0": { "display": "Iskandar", "displayTitle": "Fate/Zero", "origin": ["Fate/Zero", "Case Files Extra"], "tags": [], "portrait": "", "class": ["Servant", "Historical"] },
    "caster0": { "display": "GIlles de Rais", "displayTitle": "Fate/Zero", "origin": ["Fate/Zero"], "tags": [], "portrait": "", "class": ["Servant", "Historical"] },
    "hassanhf": { "display": "Hassan of the Hundred Faces", "displayTitle": "Fate/Zero", "origin": ["Fate/Zero"], "tags": [], "portrait": "", "class": ["Servant", "Hassan"] },
    "berserker0": { "display": "Lancelot", "displayTitle": "Fate/Zero", "origin": ["Fate/Zero"], "tags": [], "portrait": "", "class": ["Servant", "Arthurian"] },
    "kiritsugu": { "display": "Kiritsugu Emiya", "displayTitle": "Fate/Zero", "origin": ["Fate/Zero", "Fate/stay night Extra"], "tags": [], "portrait": "", "class": ["Master"] },
    "iri": { "display": "Irisviel von Einzbern", "displayTitle": "Fate/Zero", "origin": ["Fate/Zero"], "tags": [], "portrait": "", "class": ["Master"] },
    "tokiomi": { "display": "Tokiomi Tohsaka", "displayTitle": "Fate/Zero", "origin": ["Fate/Zero", "Fate/stay night Extra"], "tags": [], "portrait": "", "class": ["Master", "Clock Tower"] },
    "kayneth": { "display": "Kayneth El-Melloi Archibald", "displayTitle": "Fate/Zero", "origin": ["Fate/Zero"], "tags": [], "portrait": "", "class": ["Master", "Clock Tower"] },
    "sola": { "display": "Sola-Ui Nuada-Re Sophia-Ri", "displayTitle": "Fate/Zero", "origin": ["Fate/Zero"], "tags": [], "portrait": "", "class": ["Master", "Clock Tower"] },
    "waver": { "display": "Waver Velvet", "displayTitle": "Fate/Zero", "origin": ["Fate/Zero", "Case Files", "Fate/strange Fake"], "tags": ["lord", "zero"], "portrait": "lord", "class": ["Master", "Clock Tower"] },
    "ryuunosuke": { "display": "Ryuunosuke Uryuu", "displayTitle": "Fate/Zero", "origin": ["Fate/Zero"], "tags": [], "portrait": "", "class": ["Master"] },
    "kariya": { "display": "Kariya Matou", "displayTitle": "Fate/Zero", "origin": ["Fate/Zero"], "tags": [], "portrait": "", "class": ["Master"] },
    "risei": { "display": "Risei Kotomine", "displayTitle": "Fate/Zero", "origin": ["Fate/Zero"], "tags": [], "portrait": "", "class": ["Church"] },


    "gray": { "display": "Gray", "displayTitle": "Lord El-Melloi II's Case Files", "origin": ["Case Files", "Fate/strange Fake Extra"], "tags": [], "portrait": "", "class": ["Clock Tower"] },
    "add": { "display": "Add", "displayTitle": "Lord El-Melloi II's Case Files", "origin": ["Case Files"], "tags": [], "portrait": "", "class": ["Arthurian"] },
    "reines": { "display": "Reines El-Melloi Archisorte", "displayTitle": "Lord El-Melloi II's Case Files", "origin": ["Case Files"], "tags": [], "portrait": "", "class": ["Clock Tower"] },
    "svin": { "display": "Svin Glascheit", "displayTitle": "Lord El-Melloi II's Case Files", "origin": ["Case Files", "Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Master", "Clock Tower"] },
    "melvin": { "display": "Melvin Weins", "displayTitle": "Lord El-Melloi II's Case Files", "origin": ["Case Files"], "tags": [], "portrait": "", "class": ["Clock Tower"] },
    "faker": { "display": "Faker", "displayTitle": "Lord El-Melloi II's Case Files", "origin": ["Case Files"], "tags": [], "portrait": "", "class": ["Servant"] },
    "heartless": { "display": "Doctor Heartless", "displayTitle": "Lord El-Melloi II's Case Files", "origin": ["Case Files"], "tags": [], "portrait": "", "class": ["Master", "Clock Tower"] },
    "ergo": { "display": "Ergo", "displayTitle": "The Adventures of Lord El-Melloi II", "origin": ["Case Files"], "tags": [], "portrait": "", "class": ["Master"] },
    "ptolemy": { "display": "Ptolemy", "displayTitle": "The Adventures of Lord El-Melloi II", "origin": ["Case Files"], "tags": [], "portrait": "", "class": ["Servant", "Historical"] },


    "truesaber": { "display": "Richard I", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Servant", "Historical"] },
    "gilsf": { "display": "Gilgamesh (strange Fake)", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Servant", "Sumerian Myth"] },
    "truearcher": { "display": "Alcides", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Servant", "Greek Myth"] },
    "falselancer": { "display": "Enkidu", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Servant", "Sumerian Myth"] },
    "watcher": { "display": "Watcher", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Servant"] },
    "captain": { "display": "Captain Ahab", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Servant"] },
    "falserider": { "display": "Pale Rider", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Servant"] },
    "truerider": { "display": "Hippolyta", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Servant", "Greek Myth"] },
    "falsecaster": { "display": "Alexandre Dumas", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Servant", "Historical"] },
    "truecaster": { "display": "Fran\u00e7ois Prelati", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Servant", "Historical"] },
    "falseassassin": { "display": "No Name Assassin", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Servant", "Hassan"] },
    "hassanfr": { "display": "Hassan of the Fathomless Rift", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Servant", "Hassan"] },
    "falseberserker": { "display": "Jack the Ripper", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Servant", "Historical"] },
    "trueberserker": { "display": "Huwawa", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Servant", "Sumerian Myth"] },
    "falseayaka": { "display": "Ayaka Sajyou (strange Fake)", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake", "Fate/hollow ataraxia Extra"], "tags": [], "portrait": "", "class": ["Master"] },
    "tine": { "display": "Tin\u00e9 Chelc", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Master"] },
    "bazdilot": { "display": "Bazdilot Cordelion", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Master"] },
    "wolf": { "display": "Wolf", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Master"] },
    "sigma": { "display": "Sigma", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Master", "Servant"] },
    "tsubaki": { "display": "Tsubaki Kuruoka", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Master"] },
    "doris": { "display": "Doris Lusendra", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Master"] },
    "luvia": { "display": "Luviagelita Edelfelt", "displayTitle": "Fate/hollow ataraxia", "origin": ["Fate/hollow ataraxia", "Case Files", "Fate/strange Fake"], "tags": ["sn", "lemii", "sf"], "portrait": "sn", "class": ["Master", "Clock Tower"] },
    "orlando": { "display": "Orlando Reeve", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Master"] },
    "francesca": { "display": "Francesca Prelati", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Master"] },
    "jester": { "display": "Jester Karture", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Master"] },
    "faldeus": { "display": "Faldeus Dioland", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Master"] },
    "flat": { "display": "Flat Escardos", "displayTitle": "Fate/strange Fake", "origin": ["Case Files", "Fate/strange Fake"], "tags": ["sf", "lemii"], "portrait": "sf", "class": ["Master", "Clock Tower"] },
    "thia": { "display": "Thia Escardos", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": [] },
    "haruri": { "display": "Haruri Borzak", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Master"] },
    "trueishtar": { "display": "Ishtar (strange Fake)", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Sumerian Myth"] },
    "gugalanna": { "display": "Gugalanna", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Sumerian Myth"] },
    "hansa": { "display": "Hansa Cervantes", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Church"] },


    "redsaber": { "display": "Nero Claudius", "displayTitle": "Fate/EXTRA", "origin": ["Fate/EXTRA", "Fate/EXTRA CCC"], "tags": ["ex", "ccc"], "portrait": "ex", "class": ["Servant", "Historical"] },
    "mumei": { "display": "Nameless", "displayTitle": "Fate/EXTRA", "origin": ["Fate/EXTRA", "Fate/EXTRA CCC"], "tags": ["ex", "ccc"], "portrait": "ex", "class": ["Servant"] },
    "bluecaster": { "display": "Tamamo-no-Mae", "displayTitle": "Fate/EXTRA", "origin": ["Fate/EXTRA", "Fate/EXTRA CCC"], "tags": ["ex", "ccc"], "portrait": "ex", "class": ["Servant"] },
    "extrasaber": { "display": "Gawain", "displayTitle": "Fate/EXTRA", "origin": ["Fate/EXTRA", "Fate/EXTRA CCC"], "tags": [], "portrait": "", "class": ["Servant", "Arthurian"] },
    "extraarcher": { "display": "Robin Hood", "displayTitle": "Fate/EXTRA", "origin": ["Fate/EXTRA", "Fate/EXTRA CCC"], "tags": [], "portrait": "", "class": ["Servant", "Historical"] },
    "extralancer": { "display": "Vlad III", "displayTitle": "Fate/EXTRA", "origin": ["Fate/EXTRA"], "tags": [], "portrait": "", "class": ["Servant", "Historical"] },
    "extrarider": { "display": "Francis Drake", "displayTitle": "Fate/EXTRA", "origin": ["Fate/EXTRA"], "tags": [], "portrait": "", "class": ["Servant", "Historical"] },
    "extracaster": { "display": "Nursery Rhyme", "displayTitle": "Fate/EXTRA", "origin": ["Fate/EXTRA", "Fate/EXTRA CCC"], "tags": [], "portrait": "", "class": ["Servant"] },
    "extraassassin": { "display": "Li Shuwen", "displayTitle": "Fate/EXTRA", "origin": ["Fate/EXTRA"], "tags": [], "portrait": "", "class": ["Servant", "Historical"] },
    "extraberserker": { "display": "L\u00fc Bu", "displayTitle": "Fate/EXTRA", "origin": ["Fate/EXTRA"], "tags": [], "portrait": "", "class": ["Servant", "Historical"] },
    "arcueid": { "display": "Arcueid Brunestud", "displayTitle": "Tsukihime", "origin": ["Fate/EXTRA"], "tags": [], "portrait": "", "class": ["Servant"] },
    "saver": { "display": "Buddha", "displayTitle": "Fate/EXTRA", "origin": ["Fate/EXTRA"], "tags": [], "portrait": "", "class": ["Servant", "Historical"] },
    "hakuno": { "display": "Hakuno Kishinami (M)", "displayTitle": "Fate/EXTRA", "origin": ["Fate/EXTRA", "Fate/EXTRA CCC"], "tags": ["ex", "ccc"], "portrait": "ex", "class": ["Master"] },
    "hakunon": { "display": "Hakuno Kishinami (F)", "displayTitle": "Fate/EXTRA", "origin": ["Fate/EXTRA", "Fate/EXTRA CCC"], "tags": ["ex", "ccc"], "portrait": "ex", "class": ["Master"] },
    "leo": { "display": "Leonardo B. Harwey", "displayTitle": "Fate/EXTRA", "origin": ["Fate/EXTRA", "Fate/EXTRA CCC"], "tags": ["ex", "ccc"], "portrait": "ex", "class": ["Master"] },
    "blackmore": { "display": "Dan Blackmore", "displayTitle": "Fate/EXTRA", "origin": ["Fate/EXTRA"], "tags": [], "portrait": "", "class": ["Master"] },
    "rinex": { "display": "Rin Tohsaka (EXTRA)", "displayTitle": "Fate/EXTRA", "origin": ["Fate/EXTRA", "Fate/EXTRA CCC"], "tags": ["ex", "ccc"], "portrait": "ex", "class": ["Master"] },
    "run": { "display": "Run Ru", "displayTitle": "Fate/EXTRA", "origin": ["Fate/EXTRA"], "tags": [], "portrait": "", "class": ["Master"] },
    "shinjiex": { "display": "Shinji Matou (EXTRA)", "displayTitle": "Fate/EXTRA", "origin": ["Fate/EXTRA", "Fate/EXTRA CCC"], "tags": ["ex", "ccc"], "portrait": "ex", "class": ["Master"] },
    "alice": { "display": "Alice", "displayTitle": "Fate/EXTRA", "origin": ["Fate/EXTRA", "Fate/EXTRA CCC"], "tags": [], "portrait": "", "class": ["Master"] },
    "julius": { "display": "Julius B. Harwey", "displayTitle": "Fate/EXTRA", "origin": ["Fate/EXTRA", "Fate/EXTRA CCC"], "tags": [], "portrait": "", "class": ["Master"] },
    "rani": { "display": "Rani VIII", "displayTitle": "Fate/EXTRA", "origin": ["Fate/EXTRA", "Fate/EXTRA CCC"], "tags": ["ex", "ccc"], "portrait": "ex", "class": ["Master"] },
    "monji": { "display": "Monji Gatou", "displayTitle": "Fate/EXTRA", "origin": ["Fate/EXTRA", "Fate/EXTRA CCC"], "tags": [], "portrait": "", "class": ["Master"] },
    "twice": { "display": "Twice H. Pieceman", "displayTitle": "Fate/EXTRA", "origin": ["Fate/EXTRA"], "tags": [], "portrait": "", "class": ["Master"] },


    "gilex": { "display": "Gilgamesh (EXTRA)", "displayTitle": "Fate/EXTRA CCC", "origin": ["Fate/EXTRA CCC"], "tags": [], "portrait": "", "class": ["Servant", "Sumerian Myth"] },
    "redlancer": { "display": "Elizabeth B\u00e1thory", "displayTitle": "Fate/EXTRA CCC", "origin": ["Fate/EXTRA CCC"], "tags": [], "portrait": "", "class": ["Servant", "Historical"] },
    "lancerofred": { "display": "Karna", "displayTitle": "Fate/Apocrypha", "origin": ["Fate/EXTRA CCC"], "tags": [], "portrait": "", "class": ["Servant"] },
    "hans": { "display": "Hans Christian Andersen", "displayTitle": "Fate/EXTRA CCC", "origin": ["Fate/EXTRA CCC"], "tags": [], "portrait": "", "class": ["Servant", "Historical"] },
    "bb": { "display": "BB", "displayTitle": "Fate/EXTRA CCC", "origin": ["Fate/EXTRA CCC"], "tags": [], "portrait": "", "class": ["Master"] },
    "lip": { "display": "Passionlip", "displayTitle": "Fate/EXTRA CCC", "origin": ["Fate/EXTRA CCC"], "tags": [], "portrait": "", "class": ["Servant"] },
    "melt": { "display": "Meltryllis", "displayTitle": "Fate/EXTRA CCC", "origin": ["Fate/EXTRA CCC"], "tags": [], "portrait": "", "class": ["Servant"] },
    "jinako": { "display": "Jinako Carigiri", "displayTitle": "Fate/EXTRA CCC", "origin": ["Fate/EXTRA CCC"], "tags": [], "portrait": "", "class": ["Master"] },
    "kiara": { "display": "Kiara Sessyoin", "displayTitle": "Fate/EXTRA CCC", "origin": ["Fate/EXTRA CCC"], "tags": ["nun", "demon"], "portrait": "nun", "class": ["Master"] },
    "sakuraex": { "display": "Sakura Matou (EXTRA)", "displayTitle": "Fate/EXTRA", "origin": ["Fate/EXTRA CCC"], "tags": ["ex", "ccc"], "portrait": "ex", "class": [] }
}