let library = {
    //Fate/stay night
    "saber": { "display": "Artoria Pendragon", "displayTitle": "Fate/stay night", "origin": ["Fate/stay night", "Fate/hollow ataraxia", "Fate/Zero", "Fate/EXTELLA", "Fate/Labyrinth", "Fate/Apocrypha Extra"], "tags": ["sn", "zero", "mc"], "portrait": "sn", "class": ["Servant", "Saber", "Arthurian", "Female", "Saberface", "Genderbent", "Sovereign"] },
    "archer": { "display": "EMIYA", "displayTitle": "Fate/stay night", "origin": ["Fate/stay night", "Fate/hollow ataraxia", "Fate/EXTRA CCC Extra"], "tags": [], "portrait": "", "class": ["Servant", "Archer", "Original", "Male"] },
    "lancer": { "display": "C\u00fa Chulainn", "displayTitle": "Fate/stay night", "origin": ["Fate/stay night", "Fate/hollow ataraxia", "Fate/EXTRA", "Fate/EXTELLA", "Fate/EXTRA CCC Extra"], "tags": ["sn", "mc"], "portrait": "sn", "class": ["Servant", "Lancer", "Irish Myth", "Male"] },
    "rider": { "display": "Medusa", "displayTitle": "Fate/stay night", "origin": ["Fate/stay night", "Fate/hollow ataraxia", "Fate/EXTELLA"], "tags": ["sn", "mc"], "portrait": "sn", "class": ["Servant", "Rider", "Greek Myth", "Female"] },
    "caster": { "display": "Medea", "displayTitle": "Fate/stay night", "origin": ["Fate/stay night", "Fate/hollow ataraxia", "Fate/Labyrinth"], "tags": [], "portrait": "", "class": ["Servant", "Master", "Caster", "Greek Myth", "Female"] },
    "assassin": { "display": "Sasaki Kojirou", "displayTitle": "Fate/stay night", "origin": ["Fate/stay night", "Fate/hollow ataraxia"], "tags": [], "portrait": "", "class": ["Servant", "Assassin", "Historical", "Male"] },
    "berserker": { "display": "Heracles", "displayTitle": "Fate/stay night", "origin": ["Fate/stay night", "Fate/hollow ataraxia"], "tags": [], "portrait": "", "class": ["Servant", "Berserker", "Greek Myth", "Male"] },
    "gilsn": { "display": "Gilgamesh", "displayTitle": "Fate/stay night", "origin": ["Fate/stay night", "Fate/hollow ataraxia", "Fate/Zero"], "tags": [], "portrait": "", "class": ["Servant", "Archer", "Sumerian Myth", "Male", "Sovereign"] },
    "hassanca": { "display": "Hassan of the Cursed Arm", "displayTitle": "Fate/stay night", "origin": ["Fate/stay night", "Fate/Labyrinth"], "tags": [], "portrait": "", "class": ["Servant", "Assassin", "Hassan", "Male"] },
    "salter": { "display": "Artoria Pendragon Alter", "displayTitle": "Fate/stay night", "origin": ["Fate/stay night", "Fate/hollow ataraxia"], "tags": [], "portrait": "", "class": ["Servant", "Saber", "Arthurian", "Female", "Saberface", "Genderbent", "Sovereign"] },
    "lily": { "display": "Artoria Pendragon Lily", "displayTitle": "Fate/unlimited codes", "origin": ["Fate/stay night Extra"], "tags": [], "portrait": "", "class": ["Servant", "Saber", "Arthurian", "Female", "Saberface", "Genderbent", "Sovereign"] },
    "shirou": { "display": "Shirou Emiya", "displayTitle": "Fate/stay night", "origin": ["Fate/stay night", "Fate/hollow ataraxia", "Case Files", "Fate/Zero Extra"], "tags": ["sn", "lemii", "zero"], "portrait": "sn", "class": ["Master", "Clock Tower", "Original", "Male"] },
    "rin": { "display": "Rin Tohsaka", "displayTitle": "Fate/stay night", "origin": ["Fate/stay night", "Fate/hollow ataraxia", "Fate/Zero", "Case Files", "Fate/strange Fake", "Fate/EXTRA CCC Extra"], "tags": ["sn", "sf", "lemii", "zero"], "portrait": "sn", "class": ["Master", "Clock Tower", "Original", "Female"] },
    "kirei": { "display": "Kirei Kotomine", "displayTitle": "Fate/stay night", "origin": ["Fate/stay night", "Fate/Zero", "Fate/strange Fake Extra"], "tags": ["sn", "zero"], "portrait": "sn", "class": ["Master", "Other W", "Church", "Original", "Male"] },
    "shinji": { "display": "Shinji Matou", "displayTitle": "Fate/stay night", "origin": ["Fate/stay night", "Fate/hollow ataraxia"], "tags": [], "portrait": "", "class": ["Master", "Original", "Male"] },
    "sakura": { "display": "Sakura Matou", "displayTitle": "Fate/stay night", "origin": ["Fate/stay night", "Fate/hollow ataraxia", "Fate/Zero"], "tags": ["sn", "zero"], "portrait": "sn", "class": ["Master", "Original", "Female"] },
    "kuzuki": { "display": "Souichirou Kuzuki", "displayTitle": "Fate/stay night", "origin": ["Fate/stay night", "Fate/hollow ataraxia"], "tags": [], "portrait": "", "class": ["Master", "Original", "Male"] },
    "illya": { "display": "Illyasviel von Einzbern", "displayTitle": "Fate/stay night", "origin": ["Fate/stay night", "Fate/hollow ataraxia", "Fate/Zero Extra"], "tags": [], "portrait": "", "class": ["Master", "Original", "Female"] },
    "zouken": { "display": "Zouken Matou", "displayTitle": "Fate/stay night", "origin": ["Fate/stay night", "Fate/Zero"], "tags": [], "portrait": "", "class": ["Master", "Clock Tower", "Original", "Male"] },

    //Fate/hollow ataraxia
    "avenger": { "display": "Angra Mainyu", "displayTitle": "Fate/hollow ataraxia", "origin": ["Fate/hollow ataraxia"], "tags": [], "portrait": "", "class": ["Servant", "Avenger", "Male"] },
    "gilha": { "display": "Child Gil", "displayTitle": "Fate/hollow ataraxia", "origin": ["Fate/hollow ataraxia"], "tags": [], "portrait": "", "class": ["Servant", "Archer", "Sumerian Myth", "Male", "Sovereign"] },
    "bazett": { "display": "Bazett Fraga McRemitz", "displayTitle": "Fate/hollow ataraxia", "origin": ["Fate/hollow ataraxia"], "tags": [], "portrait": "", "class": ["Master", "Clock Tower", "Original", "Female"] },
    "caren": { "display": "Caren Hortensia", "displayTitle": "Fate/hollow ataraxia", "origin": ["Fate/hollow ataraxia"], "tags": [], "portrait": "", "class": ["Master", "Church", "Original", "Female"] },

    //Fate/Zero
    "lancer0": { "display": "Diarmuid Ua Duibhne", "displayTitle": "Fate/Zero", "origin": ["Fate/Zero"], "tags": [], "portrait": "", "class": ["Servant", "Lancer", "Irish Myth", "Male"] },
    "rider0": { "display": "Iskandar", "displayTitle": "Fate/Zero", "origin": ["Fate/Zero", "Case Files Extra", "Fate/EXTELLA"], "tags": ["zero", "mc"], "portrait": "zero", "class": ["Servant", "Rider", "Historical", "Male", "Sovereign"] },
    "caster0": { "display": "GIlles de Rais", "displayTitle": "Fate/Zero", "origin": ["Fate/Zero", "Fate/EXTELLA"], "tags": ["zero", "mc"], "portrait": "zero", "class": ["Servant", "Caster", "Historical", "Male"] },
    "hassanhf": { "display": "Hassan of the Hundred Faces", "displayTitle": "Fate/Zero", "origin": ["Fate/Zero"], "tags": [], "portrait": "", "class": ["Servant", "Assassin", "Hassan", "Male", "Female"] },
    "berserker0": { "display": "Lancelot", "displayTitle": "Fate/Zero", "origin": ["Fate/Zero", "Fate/EXTELLA"], "tags": ["zero", "mc"], "portrait": "zero", "class": ["Servant", "Berserker", "Arthurian", "Male"] },
    "kiritsugu": { "display": "Kiritsugu Emiya", "displayTitle": "Fate/Zero", "origin": ["Fate/Zero", "Fate/stay night Extra"], "tags": [], "portrait": "", "class": ["Master", "Original", "Male"] },
    "iri": { "display": "Irisviel von Einzbern", "displayTitle": "Fate/Zero", "origin": ["Fate/Zero"], "tags": [], "portrait": "", "class": ["Other W", "Original", "Female"] },
    "maiya": { "display": "Maiya Hisau", "displayTitle": "Fate/Zero", "origin": ["Fate/Zero"], "tags": [], "portrait": "", "class": ["Other W", "Original", "Female"] },
    "tokiomi": { "display": "Tokiomi Tohsaka", "displayTitle": "Fate/Zero", "origin": ["Fate/Zero", "Fate/stay night Extra"], "tags": [], "portrait": "", "class": ["Master", "Clock Tower", "Original", "Male"] },
    "kayneth": { "display": "Kayneth El-Melloi Archibald", "displayTitle": "Fate/Zero", "origin": ["Fate/Zero"], "tags": [], "portrait": "", "class": ["Master", "Clock Tower", "Original", "Male"] },
    "sola": { "display": "Sola-Ui Nuada-Re Sophia-Ri", "displayTitle": "Fate/Zero", "origin": ["Fate/Zero"], "tags": [], "portrait": "", "class": ["Master", "Clock Tower", "Original", "Female"] },
    "waver": { "display": "Waver Velvet", "displayTitle": "Fate/Zero", "origin": ["Fate/Zero", "Case Files", "Fate/strange Fake", "Fate/Apocrypha Extra", "Fate:Lost Einherjar Extra"], "tags": ["lord", "zero"], "portrait": "lord", "class": ["Master", "Clock Tower", "Original", "Male"] },
    "ryuunosuke": { "display": "Ryuunosuke Uryuu", "displayTitle": "Fate/Zero", "origin": ["Fate/Zero"], "tags": [], "portrait": "", "class": ["Master", "Original", "Male"] },
    "kariya": { "display": "Kariya Matou", "displayTitle": "Fate/Zero", "origin": ["Fate/Zero"], "tags": [], "portrait": "", "class": ["Master", "Original", "Male"] },
    "risei": { "display": "Risei Kotomine", "displayTitle": "Fate/Zero", "origin": ["Fate/Zero"], "tags": [], "portrait": "", "class": ["Other W", "Church", "Original", "Male"] },
    "blackiri": { "display": "Black Iri", "displayTitle": "Fate/Zero", "origin": ["Fate/Zero"], "tags": [], "portrait": "", "class": ["Servant", "Avenger", "Original", "Female"] },

    //El-Melloi
    "gray": { "display": "Gray", "displayTitle": "Lord El-Melloi II's Case Files", "origin": ["Case Files", "Fate/Labyrinth", "Fate/strange Fake Extra"], "tags": [], "portrait": "", "class": ["Clock Tower", "Original", "Female", "Saberface"] },
    "add": { "display": "Add", "displayTitle": "Lord El-Melloi II's Case Files", "origin": ["Case Files"], "tags": [], "portrait": "", "class": ["Arthurian", "Original", "Male"] },
    "reines": { "display": "Reines El-Melloi Archisorte", "displayTitle": "Lord El-Melloi II's Case Files", "origin": ["Case Files", "Fate/Apocrypha Extra"], "tags": [], "portrait": "", "class": ["Clock Tower", "Original", "Female"] },
    "svin": { "display": "Svin Glascheit", "displayTitle": "Lord El-Melloi II's Case Files", "origin": ["Case Files", "Fate/strange Fake", "Fate/Apocrypha Extra"], "tags": [], "portrait": "", "class": ["Master", "Clock Tower", "Original", "Male"] },
    "melvin": { "display": "Melvin Weins", "displayTitle": "Lord El-Melloi II's Case Files", "origin": ["Case Files"], "tags": [], "portrait": "", "class": ["Clock Tower", "Original", "Male"] },
    "faker": { "display": "Faker", "displayTitle": "Lord El-Melloi II's Case Files", "origin": ["Case Files"], "tags": [], "portrait": "", "class": ["Servant", "Other C", "Original", "Female"] },
    "heartless": { "display": "Doctor Heartless", "displayTitle": "Lord El-Melloi II's Case Files", "origin": ["Case Files"], "tags": [], "portrait": "", "class": ["Master", "Clock Tower", "Original", "Male"] },
    "ergo": { "display": "Ergo", "displayTitle": "The Adventures of Lord El-Melloi II", "origin": ["Case Files"], "tags": [], "portrait": "", "class": ["Master", "Original", "Male"] },
    "ptolemy": { "display": "Ptolemy", "displayTitle": "The Adventures of Lord El-Melloi II", "origin": ["Case Files"], "tags": [], "portrait": "", "class": ["Servant", "Archer", "Historical", "Male", "Sovereign"] },

    //Fate/strange Fake
    "truesaber": { "display": "Richard I", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Servant", "Saber", "Historical", "Male", "Sovereign"] },
    "gilsf": { "display": "Gilgamesh (strange Fake)", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Servant", "Archer", "Alter Ego", "Sumerian Myth", "Male", "Sovereign"] },
    "truearcher": { "display": "Alcides", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Servant", "Archer", "Avenger", "Greek Myth", "Male"] },
    "falselancer": { "display": "Enkidu", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake", "Fate/EXTRA CCC Extra"], "tags": [], "portrait": "", "class": ["Servant", "Lancer", "Sumerian Myth", "Other G"] },
    "watcher": { "display": "Watcher", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Servant", "Other C", "Biblical", "Literary", "Female"] },
    "captain": { "display": "Captain Ahab", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Servant", "Other C", "Literary", "Male"] },
    "falserider": { "display": "Pale Rider", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Servant", "Rider", "Biblical", "Other G"] },
    "truerider": { "display": "Hippolyta", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Servant", "Rider", "Greek Myth", "Female", "Sovereign"] },
    "falsecaster": { "display": "Alexandre Dumas", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Servant", "Caster", "Historical", "Male"] },
    "truecaster": { "display": "Fran\u00e7ois Prelati", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Servant", "Caster", "Historical", "Male"] },
    "falseassassin": { "display": "No Name Assassin", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Servant", "Assassin", "Hassan", "Female"] },
    "hassanfr": { "display": "Hassan of the Fathomless Rift", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Servant", "Assassin", "Hassan", "Male"] },
    "falseberserker": { "display": "Jack the Ripper", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Servant", "Berserker", "Historical", "Other G"] },
    "trueberserker": { "display": "Huwawa", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Servant", "Berserker", "Sumerian Myth", "Female"] },
    "falseayaka": { "display": "Ayaka Sajyou (strange Fake)", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake", "Fate/hollow ataraxia Extra"], "tags": [], "portrait": "", "class": ["Master", "Original", "Female"] },
    "tine": { "display": "Tin\u00e9 Chelc", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Master", "Original", "Female"] },
    "bazdilot": { "display": "Bazdilot Cordelion", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Master", "Original", "Male"] },
    "wolf": { "display": "Wolf", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Master", "Original", "Male"] },
    "sigma": { "display": "Sigma", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Master", "Servant", "Lancer", "Original", "Male"] },
    "tsubaki": { "display": "Tsubaki Kuruoka", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Master", "Original", "Female"] },
    "doris": { "display": "Doris Lusendra", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Master", "Original", "Female"] },
    "luvia": { "display": "Luviagelita Edelfelt", "displayTitle": "Fate/hollow ataraxia", "origin": ["Fate/hollow ataraxia", "Case Files", "Fate/strange Fake"], "tags": ["sn", "lemii", "sf"], "portrait": "sn", "class": ["Master", "Clock Tower", "Original", "Female"] },
    "orlando": { "display": "Orlando Reeve", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Master", "Original", "Male"] },
    "francesca": { "display": "Francesca Prelati", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Master", "Historical", "Original", "Female", "Genderbent"] },
    "jester": { "display": "Jester Karture", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Master", "Original", "Male"] },
    "faldeus": { "display": "Faldeus Dioland", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Master", "Original", "Male"] },
    "flat": { "display": "Flat Escardos", "displayTitle": "Fate/strange Fake", "origin": ["Case Files", "Fate/strange Fake", "Fate/Apocrypha Extra"], "tags": ["sf", "lemii"], "portrait": "sf", "class": ["Master", "Clock Tower", "Original", "Male"] },
    "thia": { "display": "Thia Escardos", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Other W", "Original", "Male"] },
    "haruri": { "display": "Haruri Borzak", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Master", "Original", "Female"] },
    "trueishtar": { "display": "Ishtar (strange Fake)", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Other W", "Sumerian Myth", "Female"] },
    "gugalanna": { "display": "Gugalanna", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Other W", "Sumerian Myth", "Male"] },
    "hansa": { "display": "Hansa Cervantes", "displayTitle": "Fate/strange Fake", "origin": ["Fate/strange Fake"], "tags": [], "portrait": "", "class": ["Other W", "Church", "Original", "Male"] },

    //Fate/EXTRA
    "redsaber": { "display": "Nero Claudius", "displayTitle": "Fate/EXTRA", "origin": ["Fate/EXTRA", "Fate/EXTRA CCC", "Fate/EXTELLA"], "tags": ["ex", "ccc", "venus"], "portrait": "ex", "class": ["Servant", "Saber", "Historical", "Female", "Saberface", "Genderbent", "Sovereign"] },
    "mumei": { "display": "Nameless", "displayTitle": "Fate/EXTRA", "origin": ["Fate/EXTRA", "Fate/EXTRA CCC", "Fate/EXTELLA"], "tags": ["ex", "ccc", "mullet"], "portrait": "ex", "class": ["Servant", "Archer", "Original", "Male"] },
    "bluecaster": { "display": "Tamamo-no-Mae", "displayTitle": "Fate/EXTRA", "origin": ["Fate/EXTRA", "Fate/EXTRA CCC", "Fate/EXTELLA"], "tags": ["ex", "ccc"], "portrait": "ex", "class": ["Servant", "Caster", "Japanese Myth", "Female"] },
    "extrasaber": { "display": "Gawain", "displayTitle": "Fate/EXTRA", "origin": ["Fate/EXTRA", "Fate/EXTRA CCC", "Fate/EXTELLA"], "tags": [], "portrait": "", "class": ["Servant", "Saber", "Arthurian", "Male"] },
    "extraarcher": { "display": "Robin Hood", "displayTitle": "Fate/EXTRA", "origin": ["Fate/EXTRA", "Fate/EXTRA CCC", "Fate/EXTELLA", "Fate/Labyrinth"], "tags": [], "portrait": "", "class": ["Servant", "Archer", "Historical", "Male"] },
    "extralancer": { "display": "Vlad III", "displayTitle": "Fate/EXTRA", "origin": ["Fate/EXTRA"], "tags": [], "portrait": "", "class": ["Servant", "Lancer", "Historical", "Male", "Sovereign"] },
    "extrarider": { "display": "Francis Drake", "displayTitle": "Fate/EXTRA", "origin": ["Fate/EXTRA", "Fate/EXTELLA"], "tags": ["ex", "mc"], "portrait": "ex", "class": ["Servant", "Rider", "Historical", "Female", "Genderbent"] },
    "extracaster": { "display": "Nursery Rhyme", "displayTitle": "Fate/EXTRA", "origin": ["Fate/EXTRA", "Fate/EXTRA CCC"], "tags": [], "portrait": "", "class": ["Servant", "Caster", "Original", "Literary", "Female"] },
    "extraassassin": { "display": "Li Shuwen", "displayTitle": "Fate/EXTRA", "origin": ["Fate/EXTRA", "Fate/EXTELLA"], "tags": [], "portrait": "", "class": ["Servant", "Assassin", "Historical", "Male"] },
    "extraberserker": { "display": "L\u00fc Bu", "displayTitle": "Fate/EXTRA", "origin": ["Fate/EXTRA", "Fate/EXTELLA"], "tags": [], "portrait": "", "class": ["Servant", "Berserker", "Historical", "Male"] },
    "arcueid": { "display": "Arcueid Brunestud", "displayTitle": "Tsukihime", "origin": ["Fate/EXTRA"], "tags": [], "portrait": "", "class": ["Servant", "Berserker", "Original", "Female", "Sovereign"] },
    "saver": { "display": "Buddha", "displayTitle": "Fate/EXTRA", "origin": ["Fate/EXTRA"], "tags": [], "portrait": "", "class": ["Servant", "Other C", "Historical", "Male"] },
    "hakuno": { "display": "Hakuno Kishinami (M)", "displayTitle": "Fate/EXTRA", "origin": ["Fate/EXTRA", "Fate/EXTRA CCC", "Fate/EXTELLA"], "tags": ["ex", "ccc"], "portrait": "ex", "class": ["Master", "Original", "Male", "Sovereign"] },
    "hakunon": { "display": "Hakuno Kishinami (F)", "displayTitle": "Fate/EXTRA", "origin": ["Fate/EXTRA", "Fate/EXTRA CCC", "Fate/EXTELLA"], "tags": ["ex", "ccc"], "portrait": "ex", "class": ["Master", "Original", "Female", "Sovereign"] },
    "leo": { "display": "Leonardo B. Harwey", "displayTitle": "Fate/EXTRA", "origin": ["Fate/EXTRA", "Fate/EXTRA CCC"], "tags": ["ex", "ccc"], "portrait": "ex", "class": ["Master", "Original", "Male"] },
    "blackmore": { "display": "Dan Blackmore", "displayTitle": "Fate/EXTRA", "origin": ["Fate/EXTRA"], "tags": [], "portrait": "", "class": ["Master", "Original", "Male"] },
    "rinex": { "display": "Rin Tohsaka (EXTRA)", "displayTitle": "Fate/EXTRA", "origin": ["Fate/EXTRA", "Fate/EXTRA CCC"], "tags": ["ex", "ccc"], "portrait": "ex", "class": ["Master", "Original", "Female"] },
    "run": { "display": "Run Ru", "displayTitle": "Fate/EXTRA", "origin": ["Fate/EXTRA"], "tags": [], "portrait": "", "class": ["Master", "Original", "Female"] },
    "shinjiex": { "display": "Shinji Matou (EXTRA)", "displayTitle": "Fate/EXTRA", "origin": ["Fate/EXTRA", "Fate/EXTRA CCC"], "tags": ["ex", "ccc"], "portrait": "ex", "class": ["Master", "Original", "Male"] },
    "alice": { "display": "Alice", "displayTitle": "Fate/EXTRA", "origin": ["Fate/EXTRA", "Fate/EXTRA CCC"], "tags": [], "portrait": "", "class": ["Master", "Original", "Female"] },
    "julius": { "display": "Julius B. Harwey", "displayTitle": "Fate/EXTRA", "origin": ["Fate/EXTRA", "Fate/EXTRA CCC"], "tags": [], "portrait": "", "class": ["Master", "Original", "Male"] },
    "rani": { "display": "Rani VIII", "displayTitle": "Fate/EXTRA", "origin": ["Fate/EXTRA", "Fate/EXTRA CCC"], "tags": ["ex", "ccc"], "portrait": "ex", "class": ["Master", "Original", "Female"] },
    "monji": { "display": "Monji Gatou", "displayTitle": "Fate/EXTRA", "origin": ["Fate/EXTRA", "Fate/EXTRA CCC"], "tags": [], "portrait": "", "class": ["Master", "Original", "Male"] },
    "twice": { "display": "Twice H. Pieceman", "displayTitle": "Fate/EXTRA", "origin": ["Fate/EXTRA", "Fate/EXTRA CCC Extra"], "tags": [], "portrait": "", "class": ["Master", "Original", "Male"] },

    //Fate/EXTRA CCC
    "gilex": { "display": "Gilgamesh (Classless)", "displayTitle": "Fate/EXTRA CCC", "origin": ["Fate/EXTRA CCC", "Fate/EXTELLA"], "tags": [], "portrait": "", "class": ["Servant", "Other C", "Sumerian Myth", "Male", "Sovereign"] },
    "redlancer": { "display": "Elizabeth B\u00e1thory", "displayTitle": "Fate/EXTRA CCC", "origin": ["Fate/EXTRA CCC", "Fate/EXTELLA"], "tags": [], "portrait": "", "class": ["Servant", "Lancer", "Berserker", "Historical", "Female", "Sovereign"] },
    "hans": { "display": "Hans Christian Andersen", "displayTitle": "Fate/EXTRA CCC", "origin": ["Fate/EXTRA CCC"], "tags": [], "portrait": "", "class": ["Servant", "Caster", "Historical", "Male"] },
    "bb": { "display": "BB", "displayTitle": "Fate/EXTRA CCC", "origin": ["Fate/EXTRA CCC"], "tags": [], "portrait": "", "class": ["Master", "MoonCancer", "Original", "Female"] },
    "lip": { "display": "Passionlip", "displayTitle": "Fate/EXTRA CCC", "origin": ["Fate/EXTRA CCC"], "tags": [], "portrait": "", "class": ["Servant", "Alter Ego", "Original", "Female"] },
    "melt": { "display": "Meltryllis", "displayTitle": "Fate/EXTRA CCC", "origin": ["Fate/EXTRA CCC"], "tags": [], "portrait": "", "class": ["Servant", "Alter Ego", "Original", "Female"] },
    "jinako": { "display": "Jinako Carigiri", "displayTitle": "Fate/EXTRA CCC", "origin": ["Fate/EXTRA CCC"], "tags": [], "portrait": "", "class": ["Master", "Original", "Female"] },
    "kiara": { "display": "Kiara Sessyoin", "displayTitle": "Fate/EXTRA CCC", "origin": ["Fate/EXTRA CCC"], "tags": ["nun", "demon"], "portrait": "nun", "class": ["Master", "Original", "Female"] },
    "sakuraex": { "display": "Sakura Matou (EXTRA)", "displayTitle": "Fate/EXTRA", "origin": ["Fate/EXTRA CCC", "Fate/EXTRA Extra"], "tags": ["ex", "ccc"], "portrait": "ex", "class": ["Other W", "Original", "Female"] },

    //Fate/EXTELLA
    "altera": { "display": "Altera", "displayTitle": "Fate/EXTELLA", "origin": ["Fate/EXTELLA"], "tags": ["hero, titan"], "portrait": "hero", "class": ["Servant", "Saber", "Historical", "Female", "Genderbent", "Sovereign"] },
    "archimedes": { "display": "Archimedes", "displayTitle": "Fate/EXTELLA", "origin": ["Fate/EXTELLA"], "tags": [], "portrait": "", "class": ["Servant", "Caster", "Historical", "Male"] },
    "velber02": { "display": "Sefar", "displayTitle": "Fate/EXTELLA", "origin": ["Fate/EXTELLA"], "tags": [], "portrait": "", "class": ["Original", "Female"] },

    //Fate/EXTELLA LINK
    "charlie": { "display": "Charlemagne", "displayTitle": "Fate/EXTELLA LINK", "origin": ["Fate/EXTELLA"], "tags": [], "portrait": "", "class": ["Servant", "Saber", "Historical", "Matter of France", "Male", "Sovereign"] },
    "alteralily": { "display": "Altera Larva", "displayTitle": "Fate/EXTELLA LINK", "origin": ["Fate/EXTELLA"], "tags": [], "portrait": "", "class": ["Servant", "Saber", "Historical", "Original", "Female", "Genderbent", "Sovereign"] },
    "roguearcher": { "display": "Arjuna", "displayTitle": "Fate/Samurai Remnant", "origin": ["Fate/EXTELLA"], "tags": [], "portrait": "", "class": ["Servant", "Archer", "Indian Myth", "Male"] },
    "scathach": { "display": "Sc\u00e1thach", "displayTitle": "Fate/EXTELLA LINK", "origin": ["Fate/EXTELLA"], "tags": [], "portrait": "", "class": ["Servant", "Lancer", "Irish Myth", "Female", "Sovereign"] },
    "darius": { "display": "Darius III", "displayTitle": "Fate/EXTELLA LINK", "origin": ["Fate/EXTELLA", "Fate/EXTRA Extra"], "tags": [], "portrait": "", "class": ["Servant", "Berserker", "Historical", "Male", "Sovereign"] },
    "karl": { "display": "Karl der Gro\u00dfe", "displayTitle": "Fate/EXTELLA LINK", "origin": ["Fate/EXTELLA"], "tags": [], "portrait": "", "class": ["Servant", "Ruler", "Historical", "Matter of France", "Male", "Sovereign"] },

    //Fate/Apocrypha
    "ruler": { "display": "Jeanne d'Arc", "displayTitle": "Fate/Apocrypha", "origin": ["Fate/EXTELLA", "Fate/Apocrypha"], "tags": ["apoc", "mc"], "portrait": "apoc", "class": ["Servant", "Ruler", "Historical", "Female", "Saberface"] },
    "saberofblack": { "display": "Siegfried", "displayTitle": "Fate/Apocrypha", "origin": ["Fate/Apocrypha"], "tags": [], "portrait": "", "class": ["Servant", "Saber", "Germanic Legend", "Male", "Sovereign"] },
    "archerofblack": { "display": "Chiron", "displayTitle": "Fate/Apocrypha", "origin": ["Fate/Apocrypha"], "tags": [], "portrait": "", "class": ["Servant", "Archer", "Greek Myth", "Male"] },
    "lancerofblack": { "display": "Vlad III (Apocrypha)", "displayTitle": "Fate/Apocrypha", "origin": ["Fate/Apocrypha"], "tags": [], "portrait": "", "class": ["Servant", "Lancer", "Historical", "Male", "Sovereign"] },
    "riderofblack": { "display": "Astolfo", "displayTitle": "Fate/Apocrypha", "origin": ["Fate/EXTELLA", "Fate/Apocrypha"], "tags": ["apoc", "mc"], "portrait": "apoc", "class": ["Servant", "Rider", "Matter of France", "Male"] },
    "casterofblack": { "display": "Avicebron", "displayTitle": "Fate/Apocrypha", "origin": ["Fate/Apocrypha"], "tags": [], "portrait": "", "class": ["Servant", "Caster", "Historical", "Male"] },
    "assassinofblack": { "display": "Jack the Ripper (Assassin)", "displayTitle": "Fate/Apocrypha", "origin": ["Fate/Apocrypha"], "tags": [], "portrait": "", "class": ["Servant", "Assassin", "Historical", "Female", "Genderbent"] },
    "berserkerofblack": { "display": "Frankenstein", "displayTitle": "Fate/Apocrypha", "origin": ["Fate/Apocrypha"], "tags": [], "portrait": "", "class": ["Servant", "Berserker", "Literary", "Female", "Genderbent"] },
    "saberofred": { "display": "Mordred", "displayTitle": "Fate/Apocrypha", "origin": ["Fate/Apocrypha"], "tags": [], "portrait": "", "class": ["Servant", "Saber", "Arthurian", "Female", "Saberface", "Genderbent"] },
    "archerofred": { "display": "Atalanta", "displayTitle": "Fate/Apocrypha", "origin": ["Fate/Apocrypha"], "tags": [], "portrait": "", "class": ["Servant", "Archer", "Greek Myth", "Female"] },
    "lancerofred": { "display": "Karna", "displayTitle": "Fate/Apocrypha", "origin": ["Fate/EXTRA CCC", "Fate/EXTELLA", "Fate/Apocrypha"], "tags": ["apoc", "mc"], "portrait": "apoc", "class": ["Servant", "Lancer", "Indian Myth", "Male"] },
    "riderofred": { "display": "Achilles", "displayTitle": "Fate/Apocrypha", "origin": ["Fate/Apocrypha"], "tags": [], "portrait": "", "class": ["Servant", "Rider", "Greek Myth", "Male"] },
    "casterofred": { "display": "William Shakespeare", "displayTitle": "Fate/Apocrypha", "origin": ["Fate/Apocrypha"], "tags": [], "portrait": "", "class": ["Servant", "Caster", "Historical", "Male"] },
    "assassinofred": { "display": "Semiramis", "displayTitle": "Fate/Apocrypha", "origin": ["Fate/Apocrypha"], "tags": [], "portrait": "", "class": ["Servant", "Assassin", "Female", "Other M", "Sovereign"] },
    "berserkerofred": { "display": "Spartacus", "displayTitle": "Fate/Apocrypha", "origin": ["Fate/Apocrypha"], "tags": [], "portrait": "", "class": ["Servant", "Berserker", "Historical", "Male"] },
    "gilles": { "display": "GIlles de Rais (Saber)", "displayTitle": "Fate/Apocrypha", "origin": ["Fate/Apocrypha"], "tags": [], "portrait": "", "class": ["Servant", "Other C", "Historical", "Male"] },
    "nyalter": { "display": "Atalanta Alter", "displayTitle": "Fate/Apocrypha", "origin": ["Fate/Apocrypha"], "tags": [], "portrait": "", "class": ["Servant", "Berserker", "Greek Myth", "Female"] },
    "amakusa": { "display": "Amakusa Shirou Tokisada\r", "displayTitle": "Fate/Apocrypha", "origin": ["Fate/Apocrypha"], "tags": [], "portrait": "", "class": ["Servant", "Master", "Ruler", "Church", "Historical", "Male"] },
    "sieg": { "display": "Sieg", "displayTitle": "Fate/Apocrypha", "origin": ["Fate/Apocrypha"], "tags": [], "portrait": "", "class": ["Master", "Yggdmillennia", "Original", "Male"] },
    "gordes": { "display": "Gordes Musik Yggdmillennia", "displayTitle": "Fate/Apocrypha", "origin": ["Fate/Apocrypha"], "tags": [], "portrait": "", "class": ["Master", "Yggdmillennia", "Clock Tower", "Original", "Male"] },
    "fiore": { "display": "Fiore Forvedge Yggdmillennia", "displayTitle": "Fate/Apocrypha", "origin": ["Fate/Apocrypha"], "tags": [], "portrait": "", "class": ["Master", "Yggdmillennia", "Clock Tower", "Original", "Male"] },
    "darnic": { "display": "Darnic Prestone Yggdmillennia", "displayTitle": "Fate/Apocrypha", "origin": ["Fate/Apocrypha"], "tags": [], "portrait": "", "class": ["Master", "Yggdmillennia", "Clock Tower", "Original", "Male"] },
    "celenike": { "display": "Celenike Icecolle Yggdmillennia", "displayTitle": "Fate/Apocrypha", "origin": ["Fate/Apocrypha"], "tags": [], "portrait": "", "class": ["Master", "Yggdmillennia", "Clock Tower", "Original", "Female"] },
    "roche": { "display": "Roche Frain Yggdmillennia", "displayTitle": "Fate/Apocrypha", "origin": ["Fate/Apocrypha"], "tags": [], "portrait": "", "class": ["Master", "Yggdmillennia", "Clock Tower", "Original", "Male"] },
    "reika": { "display": "Reika Rikudou\r", "displayTitle": "Fate/Apocrypha", "origin": ["Fate/Apocrypha"], "tags": [], "portrait": "", "class": ["Master", "Original", "Female"] },
    "caules": { "display": "Caules Forvedge Yggdmillennia", "displayTitle": "Fate/Apocrypha", "origin": ["Fate/Apocrypha", "Case Files Extra", "Fate/strange Fake Extra", "Fate:Lost Einherjar Extra"], "tags": ["apoc", "lemii"], "portrait": "apoc", "class": ["Master", "Yggdmillennia", "Clock Tower", "Original", "Male"] },
    "sisigou": { "display": "Kairi Sisigou", "displayTitle": "Fate/Apocrypha", "origin": ["Fate/Apocrypha", "Case Files Extra"], "tags": [], "portrait": "", "class": ["Master", "Clock Tower", "Original", "Male"] },
    "laeticia": { "display": "Laeticia", "displayTitle": "Fate/Apocrypha", "origin": ["Fate/Apocrypha"], "tags": [], "portrait": "", "class": ["Other W", "Original", "Female"] },

    //Fate:Lost Einherjar
    "lostarcher": { "display": "Aslaug", "displayTitle": "Fate:Lost Einherjar", "origin": ["Fate:Lost Einherjar"], "tags": [], "portrait": "", "class": ["Servant", "Archer", "Norse Myth", "Female"] },
    "lostberserker": { "display": "Ragnar Lodbrok", "displayTitle": "Fate:Lost Einherjar", "origin": ["Fate:Lost Einherjar"], "tags": [], "portrait": "", "class": ["Servant", "Berserker", "Norse Myth", "Male", "Sovereign"] },
    "lostlancer": { "display": "Percival", "displayTitle": "Fate:Lost Einherjar", "origin": ["Fate:Lost Einherjar"], "tags": [], "portrait": "", "class": ["Servant", "Lancer", "Arthurian", "Male"] },
    "lostrider": { "display": "Sinfj\u00f6tli", "displayTitle": "Fate:Lost Einherjar", "origin": ["Fate:Lost Einherjar"], "tags": [], "portrait": "", "class": ["Servant", "Rider", "Norse Myth", "Male"] },
    "lostcaster": { "display": "Baba Yaga? (Lost Einherjar Caster)", "displayTitle": "Fate:Lost Einherjar", "origin": ["Fate:Lost Einherjar"], "tags": [], "portrait": "", "class": ["Servant", "Caster", "Other M", "Female"] },
    "hassanle": { "display": "Unspecified Hassan? (Lost Einherjar Assassin)", "displayTitle": "Fate:Lost Einherjar", "origin": ["Fate:Lost Einherjar"], "tags": [], "portrait": "", "class": ["Servant", "Assassin", "Hassan", "Female"] },
    "lostsaber": { "display": "Saber (Lost Einherjar)", "displayTitle": "Fate:Lost Einherjar", "origin": ["Fate:Lost Einherjar"], "tags": [], "portrait": "", "class": ["Servant", "Saber"] },
    "lostavenger": { "display": "Svanhildr? (Lost Einherjar Eighth Servant)", "displayTitle": "Fate:Lost Einherjar", "origin": ["Fate:Lost Einherjar"], "tags": [], "portrait": "", "class": ["Servant", "Avenger", "Norse Myth", "Female"] },
    "lemina": { "display": "Lemina Eltfromm Yggdmillennia", "displayTitle": "Fate:Lost Einherjar", "origin": ["Fate:Lost Einherjar"], "tags": [], "portrait": "", "class": ["Master", "Yggdmillennia", "Original", "Female"] },
    "gagam": { "display": "Gagam Istorre", "displayTitle": "Fate:Lost Einherjar", "origin": ["Fate:Lost Einherjar"], "tags": [], "portrait": "", "class": ["Master", "Original", "Male"] },
    "memel": { "display": "Memel Istorre", "displayTitle": "Fate:Lost Einherjar", "origin": ["Fate:Lost Einherjar"], "tags": [], "portrait": "", "class": ["Original", "Female"] },
    "joanne": { "display": "Joanne Mellisell", "displayTitle": "Fate:Lost Einherjar", "origin": ["Fate:Lost Einherjar"], "tags": [], "portrait": "", "class": ["Master", "Original", "Female"] },
    "maltheim": { "display": "Maltheim", "displayTitle": "Fate:Lost Einherjar", "origin": ["Fate:Lost Einherjar"], "tags": [], "portrait": "", "class": ["Master", "Original", "Male"] },
    "bragi": { "display": "Bragi", "displayTitle": "Fate:Lost Einherjar", "origin": ["Fate:Lost Einherjar"], "tags": [], "portrait": "", "class": ["Original", "Male"] },
    "lagertha": { "display": "Lagertha", "displayTitle": "Fate:Lost Einherjar", "origin": ["Fate:Lost Einherjar"], "tags": [], "portrait": "", "class": ["Norse Myth", "Female"] },

    //Fate/Prototype
    "protosaber": { "display": "Arthur Pendragon", "displayTitle": "Fate/Prototype", "origin": ["Fate/Prototype", "Fate/Prototype: Fragments"], "tags": ["proto", "frags"], "portrait": "proto", "class": ["Servant", "Saber", "Arthurian", "Male", "Sovereign"] },
    "gilp": { "display": "Gilgamesh (Prototype)", "displayTitle": "Fate/Prototype", "origin": ["Fate/Prototype"], "tags": [], "portrait": "", "class": ["Servant", "Archer", "Sumerian Myth", "Male", "Sovereign"] },
    "protocu": { "display": "C\u00fa Chulainn (Prototype)", "displayTitle": "Fate/Prototype", "origin": ["Fate/Prototype"], "tags": [], "portrait": "", "class": ["Servant", "Lancer", "Irish Myth", "Male"] },
    "perseus": { "display": "Perseus", "displayTitle": "Fate/Prototype", "origin": ["Fate/Prototype", "Fate/hollow ataraxia Extra"], "tags": [], "portrait": "", "class": ["Servant", "Rider", "Greek Myth", "Male", "Sovereign"] },
    "protoherc": { "display": "Heracles (Prototype)", "displayTitle": "Fate/Prototype", "origin": ["Fate/Prototype"], "tags": [], "portrait": "", "class": ["Servant", "Berserker", "Greek Myth", "Male"] },
    "beast666": { "display": "Beast of 666", "displayTitle": "Fate/Prototype", "origin": ["Fate/Prototype"], "tags": [], "portrait": "", "class": ["Servant", "Other C", "Other G"] },
    "trueayaka": { "display": "Ayaka Sajyou", "displayTitle": "Fate/Prototype", "origin": ["Fate/Prototype", "Fate/strange Fake Extra"], "tags": [], "portrait": "", "class": ["Master", "Clock Tower", "Original", "Female"] },
    "archermaster": { "display": "Archer's Master (Prototype)", "displayTitle": "Fate/Prototype", "origin": ["Fate/Prototype"], "tags": [], "portrait": "", "class": ["Master", "Original", "Male"] },
    "misaya": { "display": "Misaya Reiroukan", "displayTitle": "Fate/Prototype", "origin": ["Fate/Prototype", "Fate/Prototype: Fragments"], "tags": ["proto", "frags"], "portrait": "proto", "class": ["Master", "Original", "Female"] },
    "aro": { "display": "Aro Isemi", "displayTitle": "Fate/Prototype", "origin": ["Fate/Prototype"], "tags": [], "portrait": "", "class": ["Master", "Original", "Male"] },
    "sancraid": { "display": "Sancraid Phahn", "displayTitle": "Fate/Prototype", "origin": ["Fate/Prototype"], "tags": [], "portrait": "", "class": ["Master", "Other W", "Church", "Original", "Male"] },
    "manaka": { "display": "Manaka Sajyou", "displayTitle": "Fate/Prototype", "origin": ["Fate/Prototype", "Fate/Prototype: Fragments", "Fate/Labyrinth"], "tags": ["frags", "proto"], "portrait": "frags", "class": ["Master", "Original", "Female"] },

    //Fate/Prototype Fragments
    "protoarcher": { "display": "Arash", "displayTitle": "Fate/Prototype: Fragments of Sky Silver", "origin": ["Fate/Prototype: Fragments"], "tags": [], "portrait": "", "class": ["Servant", "Archer", "Other M", "Male"] },
    "protolancer": { "display": "Brynhildr", "displayTitle": "Fate/Prototype: Fragments of Sky Silver", "origin": ["Fate/Prototype: Fragments"], "tags": [], "portrait": "", "class": ["Servant", "Lancer", "Norse Myth", "Female"] },
    "protorider": { "display": "Ozymandias", "displayTitle": "Fate/Prototype: Fragments of Sky Silver", "origin": ["Fate/Prototype: Fragments"], "tags": [], "portrait": "", "class": ["Servant", "Rider", "Biblical", "Historical", "Male", "Sovereign"] },
    "protocaster": { "display": "Paracelsus von Hohenheim", "displayTitle": "Fate/Prototype: Fragments of Sky Silver", "origin": ["Fate/Prototype: Fragments"], "tags": [], "portrait": "", "class": ["Servant", "Caster", "Historical", "Male"] },
    "hassans": { "display": "Hassan of Serenity", "displayTitle": "Fate/Prototype: Fragments of Sky Silver", "origin": ["Fate/Prototype: Fragments"], "tags": [], "portrait": "", "class": ["Servant", "Assassin", "Hassan", "Female"] },
    "protoberserkerj": { "display": "Henry Jekyll", "displayTitle": "Fate/Prototype: Fragments of Sky Silver", "origin": ["Fate/Prototype: Fragments"], "tags": [], "portrait": "", "class": ["Servant", "Berserker", "Literary", "Male"] },
    "protoberserkerh": { "display": "Hyde", "displayTitle": "Fate/Prototype: Fragments of Sky Silver", "origin": ["Fate/Prototype: Fragments"], "tags": [], "portrait": "", "class": ["Servant", "Berserker", "Literary", "Male"] },
    "elza": { "display": "Elza Saijo", "displayTitle": "Fate/Prototype: Fragments of Sky Silver", "origin": ["Fate/Prototype: Fragments"], "tags": [], "portrait": "", "class": ["Master", "Original", "Female"] },
    "nigel": { "display": "Nigel Saward", "displayTitle": "Fate/Prototype: Fragments of Sky Silver", "origin": ["Fate/Prototype: Fragments"], "tags": [], "portrait": "", "class": ["Master", "Clock Tower", "Original", "Male"] },
    "shizuri": { "display": "Shizuri Isemi", "displayTitle": "Fate/Prototype: Fragments of Sky Silver", "origin": ["Fate/Prototype: Fragments"], "tags": [], "portrait": "", "class": ["Master", "Original", "Male"] },
    "aritoshi": { "display": "Aritoshi Reiroukan", "displayTitle": "Fate/Prototype: Fragments of Sky Silver", "origin": ["Fate/Prototype: Fragments"], "tags": [], "portrait": "", "class": ["Master", "Original", "Male"] },
    "seiji": { "display": "Seiji Jinga", "displayTitle": "Fate/Prototype: Fragments of Sky Silver", "origin": ["Fate/Prototype: Fragments"], "tags": [], "portrait": "", "class": ["Master", "Original", "Male"] },
    "tatsumi": { "display": "Tatsumi Kitano", "displayTitle": "Fate/Prototype: Fragments of Sky Silver", "origin": ["Fate/Prototype: Fragments"], "tags": [], "portrait": "", "class": ["Master", "Original", "Male"] },
    "hiroki": { "display": "Hiroki Sajyou", "displayTitle": "Fate/Prototype: Fragments of Sky Silver", "origin": ["Fate/Prototype: Fragments"], "tags": [], "portrait": "", "class": ["Other P", "Original", "Male"] },

    //Fate/Labyrinth
    "asterios": { "display": "Asterios", "displayTitle": "Fate/Labyrinth", "origin": ["Fate/Labyrinth"], "tags": [], "portrait": "", "class": ["Servant", "Berserker", "Greek Myth", "Male"] },
    "norma": { "display": "Norma Goodfellow", "displayTitle": "Fate/Labyrinth", "origin": ["Fate/Labyrinth"], "tags": [], "portrait": "", "class": ["Master", "Original", "Female"] },
    "wolfgang": { "display": "Wolfgang Faustus", "displayTitle": "Fate/Labyrinth", "origin": ["Fate/Labyrinth"], "tags": [], "portrait": "", "class": ["Master", "Original", "Male"] }
}